#! /usr/bin/env bash

# Trace this script
set -x

# Ensure that we are running Bash. Set safe defaults.
set -euo pipefail

# Ensure that we have 'make', and print version debugging info.
make --version

# Ensure that we have 'opam', and print version.
opam --version

export OPAMROOT=../opam

# Configure the shell according to the Makefile-prescribed configuration for Opam.
make opam_init
eval "$(opam env)"

# Ensure that we have Ocaml, and its utilities (include Dune), at hand.
command -v ocaml
command -v ocamlopt
command -v dune
ocaml --version
dune --version
rustup --version
go version

# Make various targets, in dependency order.
make ocaml_version
make ocaml_word_size
make ocaml_checks
make reformat-diff
make libp2p_helper
make build
